name: Release Build

on:
  release:
    types: [created]
    branches: [main]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Write perms for gradlew
          run: chmod +x ./gradelw

        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
              java-version: 1.8

        - name: Build application
          run: ./gradelw buildDebug

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
              name: Apk Build
              path: ./RPS.apk

        - name: update release
          id: update_release
          uses: tubone24/update_release@v1.0
          env:
               GITHUB_TOKEN: ${{ github.token }}


                
