name: Release Build

on:
  release:
    types: [created]
    branches: [main]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Write perms for gradlew
          run: chmod +x ./gradlew

        - name: set up JDK 11
          uses: actions/setup-java@v1
          with:
              java-version: 11

        - name: Build application
          run: ./gradlew buildDebug

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
              name: Apk Build
              path: ./RPS.apk
               
        - name: update release
          id: update_release
          uses: tubone24/update_release@v1.0
          env:
            GITHUB_TOKEN: ${{ github.token }}
            
        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.github_token }}
          with:
            upload_url: ${{ steps.update_release.outputs.upload_url }}
            asset_path: ./RPS.apk
            asset_name: RPS.apk
            asset_content_type: ${{ matrix.asset_content_type }}
